version: '3.7'

services:

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: mailhog
    networks:
      - jenkins
    ports:
      - "1025:1025"
      - "8025:8025"

  jenkins:
    image: myjenkins-blueocean:2.414.2
    container_name: jenkins-docker-compose-test
    networks:
      - jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home

networks:
  jenkins:

volumes:
  jenkins-data:
